jobs:
  - name: myProvisionJob
    type: runSh
    steps:
      - IN: myGithubRepo
      - IN: myGclCliConfig
      - TASK:
        # Execute Ansible playbook
        - script: export email="$(echo "$MYGCLCLICONFIG_INTEGRATION_JSON_KEY" | jq -r '.client_email')" 
        - script: export projectId="$(echo "$MYGCLCLICONFIG_INTEGRATION_JSON_KEY" | jq -r '.project_id')"
        - script: echo "$email"
        - script: |
            cd $MYGITHUBREPO_STATE  
            ansible-playbook -v google-cloud-provision.yml
