jobs:                            
  - name: sample_php_runCI              
    type: runCI                         
    steps:                               
      - IN: nightly-trigger              
    on_success:                          
      - script: echo 'on success !!!!!'  
    on_failure:                          
      - script: echo 'Failed job .... :('
