jobs:
  - name: myProvisionJob
    type: runSh
    steps:
      - IN: myGithubRepo
      - IN: myGclCliConfig
      - TASK:
        # Execute Ansible playbook
        #- script: export email="$(echo "$MYGCLCLICONFIG_INTEGRATION_JSON_KEY" | jq -r '.client_email')" 
        #- script: export projectId="$(echo "$MYGCLCLICONFIG_INTEGRATION_JSON_KEY" | jq -r '.project_id')"
        - script: pwd
        - script: ls -al
        - script: export int_path="$(shipctl get_resource_meta "$MYGCLCLICONFIG_NAME")/key.json"
        - script: export email="$(shipctl get_json_value "key.json" "client_email")"
        - script: export projectId="$(shipctl get_json_value "key.json" "project_id")"
        - script: echo "$email"
        - script: |
            cd $MYGITHUBREPO_STATE  
            ansible-playbook -v google-cloud-provision.yml
