jobs:
  - name: app
    type: manifest
    steps:
     - IN: app_image1_nginx
     #- IN: deploy-gke-basic-docker-options
     #- IN: deploy-gke-basic-params
     #- IN: deploy-gke-basic-replicas
  - name: appdeployjobdcl
    type: deploy
    #method: upgrade
    #method: replace
    steps:
      - IN: app
      - IN: op_cluster1_dcl
