jobs:
  - name: app_service_def1
    type: manifest
    steps:
     - IN: app_image1
  - name: appdeployjob1
    type: deploy
    #method: upgrade
    method: replace
    steps:
      - IN: app_service_def1
      - IN: op_cluster1
