jobs:
  - name: wokker
    type: manifest
    on_success:
      - NOTIFY: irc
    on_start:
      - NOTIFY: irc
    on_failure:
      - NOTIFY: irc
    steps:
      - IN: box-nginx
      - IN: trigger-dv-man
