jobs:
  - name: app_service_def1
    type: manifest
    steps:
     - IN: app_image1
     - IN: deploy-gke-basic-docker-options
     - IN: deploy-gke-basic-params
     - IN: deploy-gke-basic-replicas
  - name: appdeployjob1
    type: deploy
    #method: upgrade
    #method: replace
    steps:
      - IN: app_service_def1
      - IN: op_cluster1
